dist: xenial

language: java

jdk: openjdk17

addons:
  apt:
    update: true

jobs:
  include:
    - stage: build
      script:
        - mvn clean install -DskipTests
    - stage: verify
      script:
        - mvn verify jacoco:report coveralls:report