dist: focal

language: java

jdk: openjdk17

addons:
  apt:
    update: true

jobs:
  include:
    - stage: build and install project
      script:
        - mvn clean install -DskipTests
    - stage: verify and generate coverage report
      script:
        - mvn verify jacoco:report coveralls:report